### ISSUE TITLE
Double free memory exception during shutdown

### ISSUE THREAD

**Issue by svenorth** [GENIVI/AudioManager#11]
Behavior:
Shutdown the GAM leads to a double free memory exception.

Expected behavior:
No exception during shutdown procedure.

GAM setup:
cmake -DWITH_DOCUMENTATION=OFF -DWITH_TESTS=OFF -DWITH_DLT=OFF -DWITH_TELNET=OFF -DWITH_DBUS_WRAPPER=ON -DWITH_CAPI_WRAPPER=OFF -DWITH_SYSTEMD_WATCHDOG=OFF -DCMAKE_BUILD_TYPE=Debug ..

Plugin setup:
cmake -DWITH_DOCUMENTATION=ON -DWITH_COMMAND_INTERFACE_DBUS=ON -DWITH_GENERIC_CONTROLLER=ON -DCMAKE_BUILD_TYPE=Debug ..

Trace:
[gam_shutdown_error.txt](https://github.com/GENIVI/AudioManager/files/748059/gam_shutdown_error.txt)

**Comment by GeniviAMmaintainer** [comment]
most likely due to generic controller, please check with the controller what is happening here.
