### ISSUE TITLE
Signal term is not handled immediately

### ISSUE THREAD

**Issue by svenorth** [GENIVI/AudioManager#12]
Behavior:
Sent signal term to GAM but process did not terminate. After sending a dbus message the signal was handled correctly.

Expected behavior:
GAM terminates immediately.

GAM setup:
cmake -DWITH_DOCUMENTATION=OFF -DWITH_TESTS=OFF -DWITH_DLT=OFF -DWITH_TELNET=OFF -DWITH_DBUS_WRAPPER=ON -DWITH_CAPI_WRAPPER=OFF -DWITH_SYSTEMD_WATCHDOG=OFF -DCMAKE_BUILD_TYPE=Debug ..

Plugin setup:
cmake -DWITH_DOCUMENTATION=ON -DWITH_COMMAND_INTERFACE_DBUS=ON -DWITH_GENERIC_CONTROLLER=ON -DCMAKE_BUILD_TYPE=Debug ..

Proposal:
Use non blocking read operation in GAM main loop.

**Comment by GeniviAMmaintainer** [comment]
most likely due to generic controller, please check with the controller what is happening here.

**Comment by svenorth** [comment]
Are you sure? The Audio Manager uses ppoll thus the signals SIGINT, SIGTERM, ... are blocked.

**Comment by GeniviAMmaintainer** [comment]
with the new pull request, we have implemented sigfd. please recheck if this fixed the bug

**Comment by GeniviAMmaintainer** [comment]
https://github.com/GENIVI/AudioManager/pull/16

**Comment by JensLorenz** [comment]
PR#16 merged since a long time. The bug can be closed.
