### ISSUE TITLE
make DltWrapper more public?

### ISSUE THREAD

**Issue by zeerd** [GENIVI/AudioManager#17]
dlt-daemon would not accept any issue , so a commit this here.

Could you guys move the CAmDltWrapper.cpp and CAmDltWrapper.h into dlt-daemon, so that people using cpp could easily use your codes with dlt?

**Comment by GeniviAMmaintainer** [comment]
Hi,

I had a brief talk to our dlt guys. They would like to have such an approach (more general of course) and suggested to contact them using the dlt mailing list or directly open a pull request on github.

**Comment by zeerd** [comment]
thank you. and i will close this.
