### ISSUE TITLE
Clean up whitespace

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/AudioManager#24]
If I could see correctly, about half the files use spaces only and about half use only TABs, or some tabs.
(There are several files that are mixed!)

I would like to request:

1. Maintainer defines a code style for this project, and document it (for example in README and/or CONTRIBUTION).  @jeremiah can help to give pointers to recommended content in README and such files.
2. Make a single commit fixing all files to the chosen code style.
3. (Consider defining a .clang-format style file file to make it easier to keep things in check using [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)).

**Comment by JensLorenz** [comment]
Actually there is an IDE format definition for Eclipse. Please see:
https://github.com/GENIVI/AudioManager/blob/master/Foo/AudioManagerCodestyle.xml

I have adapted the code style by one aspect on my side and run the formatting tool of the IDE.
The result will be available within next PR together with the README update.

**Comment by gunnarx** [comment]
> Actually there is an IDE format definition for Eclipse. Please see:
> https://github.com/GENIVI/AudioManager/blob/master/Foo/AudioManagerCodestyle.xml

Thanks for the pointer, I'm glad to see that.  If it can be documented (point users to the existence of the file), that's good.

**Comment by JensLorenz** [comment]
@gunnarx In the meantime I have figured out that the respective section is already in README.

**Comment by gunnarx** [comment]
Just a small update and reference:  #31 (merged) updated the indentation rules file mentioned above, so that's the starting point for cleaning indentation and whitespace.  I have considered various "quality" updates for a PR some time, but I have  no bandwidth to complete it right now.  Maybe in the future, or someone else does it first.
