### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/AudioManager#27]

**Comment by JensLorenz** [comment]
@gunnarx: Why this issue. There is an update of the documentation in PR#25.
Shall we close it?

**Comment by gunnarx** [comment]
Sorry, something went wrong here - I had a long text describing what inconsistencies I found, but it was lost.

**Comment by gunnarx** [comment]
If you'll accept that this is not perfect, let me repeat from memory (and maybe some detail wrong):
- The GENIVI wiki points to docs.projects.genivi.org which has an outdated doxygen.  Fix Wiki and ask for the old docs to be taken down.  There are two wiki pages (project summary, and a more detailed page).  Make sure we have only up to date pointers to the right location (primarily GitHub nowadays).
- HTML files are in docs/ on master, but really only needed on gh_pages branch.
- The current gh_pages are for "7.5.11" but there is no such tagged software version, so that leads to a related question - there are tags for 7.4/7.5/7.6, and so on but this suggests there are 11 patch releases in between.  How does that match?
- The gh_pages are not up to date with 7.6 (I guess that's what #25 solves?)
- I was wondering about setting up automation to make the gh_pages always up to date with master branch.

**Comment by gunnarx** [comment]
@GeniviAMmaintainer - I'm expecting you will answer & take care of most of these.  If there's an issue, let us know please.

**Comment by GeniviAMmaintainer** [comment]
Updated docs in gh_pages branch. Unfortunately I cannot modify the wiki pages - I don't have writing access to it.

**Comment by GeniviAMmaintainer** [comment]
@gunnarx : IMO it makes sense to have the latest docs in the master as well. So the master is always up to date and can be merged to the gh_pages whenever a new version has been released.

**Comment by gunnarx** [comment]
OK, it's up to you.  I thought it was not a straight git-merge because they are in different directories?  (But maybe git handles that by looking at history somehow?).   

For the GENIVI public Wiki you can sign up for account via [JIRA login](https://at.projects.genivi.org/jira/login.jsp) page.

**Comment by GeniviAMmaintainer** [comment]
Updated wiki links

**Comment by JensLorenz** [comment]
I guess the issue can be closed now?
