### ISSUE TITLE
 Add API to command interface to get current volume from a sink

### ISSUE THREAD

**Issue by GeniviAMmaintainer** [GENIVI/AudioManager#3]
Was bug #397 entered by  Pau Espin Pedrol 
There's currently no easy way to get the current volume value of a sink, which is usually needed for HMIs which want to show and change the volume of a given sink.

My proposal is to add a method similar to the following:
am_Error_e getVolume(const am_sinkID_t sinkID, am_mainVolume_t & volume);

Check this ML threads for original context:
http://lists.genivi.org/pipermail/genivi-audio-manager/2015-September/000289.html

**Comment by JensLorenz** [comment]
Isn't the getVolume() already implemented on command side?
I assume we can close the ticket.
