### ISSUE TITLE
Failed to cmake the AudioManagerPlugins Project

### ISSUE THREAD

**Issue by ShafiqAiman94** [GENIVI/AudioManager#44]
Hi , every time I want to compile the AudioManagerPlugins project. I got this error

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
AudioManagerUtilities_LIBRARY
    linked by target "PluginControlInterfaceGeneric" in directory /home/peter/Desktop/Clarion/Himawari/audio-manager/AudioManagerPlugins/PluginControlInterfaceGeneric
    linked by target "PluginCommandInterfaceDbus" in directory /home/peter/Desktop/Clarion/Himawari/audio-manager/AudioManagerPlugins/PluginCommandInterfaceDbus

Anyone know how to solve this issue?

**Comment by JensLorenz** [comment]
Is your cmake  configuration and the include files of AudioManager copied to a central place?
Cmake of plugins demands the configuration and the header files in order to configure and compile correctly.

**Comment by ShafiqAiman94** [comment]
I got it.Thanks
