### ISSUE TITLE
No such file or directory at running AudioManager

### ISSUE THREAD

**Issue by alrdguez** [GENIVI/AudioManager#5]
After compiling and installing AudioManager in GDP SDE 11 on a virtual machine, trying to run "AudioManager" at /usr/local/bin it doesnt recognize it. The output is "No such file or directory" 

The output of "file AudioManager" is  

AudioManager: ELF 64-bit LSB  executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=76a2001416aad94ddb62e5fe13d76c7592078da0, not stripped 

After running cmake we have disable the TELNET flag and activated the DBUS flag at the CMakeLists.txt
I dont think this is a relevant fact but there is

Is this a known bug? Am I doing something wrong?
Many Thanks

**Comment by GeniviAMmaintainer** [comment]
hu.. sorry just saw it.
The audiomanager needs at least one command one routing and exactly one control plugin for it to run. If he cannot find the plugins, he will not work.
Please check the brother repository for the plugins. There you can compile sample plugins:
https://github.com/GENIVI/AudioManagerPlugins
